[package]
name = "rust_shm"
version = "0.1.0"
edition = "2021"
authors = ["Jeffrey Qian"] # contact this man if he still exists

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen="0.60.1"
