# Builds the docker container using gitlab ci
# TODO: This uses gitlab variables, which is not secure at all. Should
# transition to using vault at some point
# see https://gitlab.cuauv.org/help/ci/secrets/index.md

stages:
  - build
  - push
  - open-source


build-job:
  stage: build
  script:
    - echo "Building cuauv:$CI_COMMIT_BRANCH"
    - docker build -t docker.cuauv.org/cuauv:$CI_COMMIT_BRANCH .

push-job:
  stage: push
  script:
    # TODO: provide username and password through secrets
    # - docker login docker.cuauv.org -u $DOCKER_LOGIN_USERNAME -p $DOCKER_LOGIN_PASSWORD
    - docker push docker.cuauv.org/cuauv:$CI_COMMIT_BRANCH

# Disabled, remove . to enable
.open-source-job:
  stage: open-source
  only:
    - master
  script: 
    - bash open-source/update.sh
