from typing import Callable
def get_camera(results_group: any) -> any: ...
def get_camera_size(results_group: any) -> any: ...
def get_camera_center(results_group: any) -> any: ...
def get_sub_quaternion(kalman: any) -> any: ...
def get_sub_position(kalman: any) -> any: ...
def call_if_function(value: any) -> any: ...
def within_deadband(a: any, b: any, deadband: any, use_mod_error: any) -> any: ...
def should_run(task: any, finite: any) -> any: ...
def should_finish(task: any, finite: any) -> any: ...
def dict_join(d1: any, d2: any) -> any: ...
