# Thruster Positions and Angles are correct however we dont know if buoyancy stuff is correct

#should be correct. Even if they are not, values are similar enough to polaris that I don't think will break things.
center_of_buoyancy = [0.0, -0.001873199573, -0.01898001599]
# GOOGLE SHEET: center_of_buoyancy = [0.01174093635, -0.001873199573, -0.01898001599]
buoyancy_force = 370 # Sheet: 451.75191481
gravity_force = 363.05437581 #in newtons

#did not change
# only used for partially submerged buoyancy force calculation, non critical
sub_height = 0.50

# Moments of inertia (kg * m^2) from solidworks.
# In the model frame.
dvl_offset = 0.08056941238630762
dvl_reversed = true
dvl_scaling_factor = 1

 
#confident is correct. Past years directly copied from mechies sheet, so I did the same.
I = [[ 0.978,  0.172, 0.118],
     [-0.167,  0.985, -0.053],
     [-0.125, 0.033,  0.992]]

#did not change
# Ib and body_rot calculated using auv-body-frame-calc.
Ib = [1.0, 1.0, 1.0]
# A normalized quaternion representing rotation from the body to the model frame.
btom_rq = [1.0, 0.0, 0.0, 0.0]
# x was tweaked to reflect the limited real backwards thrust of our thrusters.
cwhe_axes = [20.0, 20.0, 40.0, 40.0, 40.0, 40.0]
thruster_minimums = [-20.0, -20.0, -40.0, -40.0, -40.0, -40.0]
thruster_maximums = [20.0, 20.0, 40.0, 40.0, 40.0, 40.0]

quaternion_filtering = 1
dvl_present = true
use_dvl_for_depth = false
water_depth = 4.2672

gx_hpr = [180.0, 0.0, 0.0] # Note: You probably want to re-tare the GX rather than use this offset

[measurement_error]
velSigma = 0.005
depthSigma = 1.0
accSigma = 1000.0


#need to check that these corespond to the correct motors on sirius but 
#the pos and heading_pitch should match
[[thrusters]]
name = "sway_aft"
debug_name = "Depth Fore Port"
type = "T200"
pos = [0.15875, -0.309118, 0.053086]
heading_pitch = [0.0, 90.0]
reversed = true
broken = false

[[thrusters]]
name = "aft_port"
debug_name = "Depth Fore Star"
type = "T200"
pos = [0.15875, 0.3175, 0.53086]
heading_pitch = [0.0, 90.0]
reversed = true
broken = false

[[thrusters]]
name = "port"
debug_name = "Depth Aft Star"
type = "T200"
pos = [-0.1524, 0.3175, 0.053086]
heading_pitch = [0.0, 90.0]
reversed = true
broken = false

[[thrusters]]
name = "fore_starboard"
debug_name = "Depth Aft Port"
type = "T200"
pos = [-0.1524, -0.309118, 0.053086]
heading_pitch = [0.0, 90.0]
reversed = false
broken = false

[[thrusters]]
name = "sway_fore"
debug_name = "Diagonal Fore Port"
type = "T200"
pos = [0.282194, -0.299212, -0.036068]
heading_pitch = [45.0, 0.0]
reversed = true
broken = false

[[thrusters]]
name = "fore_port" 
debug_name = "Diagonal Fore Star"
type = "T200"
pos = [0.282194, 0.30734, -0.036068]
heading_pitch = [315.0, 0.0]
reversed = true
broken = false

[[thrusters]]
name = "aft_starboard"
debug_name = "Diagonal Aft Star"
type = "T200"
pos = [-0.269494, 0.30734, -0.036068]
heading_pitch = [225.0, 0.0]
reversed = true
broken = false

[[thrusters]]
name = "starboard"
debug_name = "Diagonal Aft Port"
type = "T200"
pos = [-0.269494, -0.299212, -0.036068]
heading_pitch = [135.0, 0.0]
reversed = true
broken = false

#directly copied from polaris as a starting point
[control_settings]
depth   = { kP = 6.00, kI = 0.06, kD = 12.00, rD = 0.30, ramp_speed = 0.5 }
pitch   = { kP = 0.30, kI = 0.03, kD = 5.00, rD = 30.0 }
heading = { kP = 0.30, kI = 0.03, kD = 10.00, rD = 30.0 }
roll    = { kP = 0.30, kI = 0.03, kD = 2.50, rD = 30.0 }
velx    = { kP = 8.30, kI = 0.12, kD = 0.50, rD = 0.1547 }
vely    = { kP = 6.00, kI = 0.20, kD = 1.00, rD = 0.5 }
quat    = { kP = 30.0, kI = 0.00, kD = 4.00 }

# depth   = { kP = 2.60, kI = 0.04, kD = 5.00, rD = 0.30, ramp_speed = 0.5 }
# pitch   = { kP = 0.10, kI = 0.02, kD = 5.00, rD = 30.0 }
# heading = { kP = 0.30, kI = 0.03, kD = 14.00, rD = 20.0 }
# velx    = { kP = 8.30, kI = 0.12, kD = 0.50, rD = 0.1547 }
# vely    = { kP = 6.00, kI = 0.20, kD = 1.00, rD = 0.5 }
# roll    = { kP = 0.10, kI = 0.00, kD = 2.00, rD = 30.0 }
# quat    = { kP = 30.0, kI = 0.00, kD = 4.00 }


#did not change rest of this.
# horizontal, produces drag when diving and pitching
[[drag_planes]]
pos = [0.25, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
cD = 2.0
area = 0.35

[[drag_planes]]
pos = [-0.25, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
cD = 2.0
area = 0.35

# fore sway, produces drag when swaying and rolling
[[drag_planes]]
pos = [0.0, 0.0, -0.10]
normal = [0.0, 1.0, 0.0]
cD = 2.0
area = 0.20

# aft sway
[[drag_planes]]
pos = [0.0, 0.0, 0.10]
normal = [0.0, 1.0, 0.0]
cD = 2.0
area = 0.20

# vertical, produces drag when going forward and yawing
[[drag_planes]]
pos = [0.0, -0.25, 0.0]
normal = [1.0, 0.0, 0.0]
cD = 2.0
area = 0.10

[[drag_planes]]
pos = [0.0, 0.25, 0.0]
normal = [1.0, 0.0, 0.0]
cD = 2.0
area = 0.10

[sensors]
heading = "gx4.heading"
pitch = "gx4.pitch"
roll = "gx4.roll"

heading_rate = "gx4.ratez"
pitch_rate = "gx4.ratey"
roll_rate = "gx4.ratex"

velx = "dvl.velocity_x"
vely = "dvl.velocity_y"
velz = "dvl.velocity_z"

accelx = "gx4.accelx"
accely = "gx4.accely"
accelz = "gx4.accelz"

depth = "depth.depth"
dvl_altitude = "dvl.savg_altitude"
depth_offset = "depth.offset_mainsub"
quaternion = "gx4"

[actuators]
bottom_torpedo = 8
top_torpedo = 4
manipulator_grab = 9
manipulator_release = 2

[vision_modules.record]
capture_sources = ["forward", "downward", "depth", "normal"]

[vision_modules.poster]
capture_sources = ["forward", "downward", "depth", "normal"]

[vision_modules.calibrate]
capture_sources = ["forward"]

[vision_modules.find_red]
capture_sources = ["forward"]

[cameras.downward]
type = "ueye"
id = 0
camera_name = "ueye_downward_ajax" # for configuration
width = 640
height = 512
position = [0.48, 0.15, -0.08]
orientation_hpr = [0.0, 0.0, 0.0]
rotate180 = true
rotate90 = false
# The optical sensor size of the CAMERA, width and height in mm
# This should typically be in the same ratio as the resolution, above.
sensor_size_wh_mm = [4.995, 3.746]
# The focal length of the LENS in mm
focal_length_mm = 3.5

[cameras.forward]
type = "zed"
id = 3
camera_name = "zed_forward_sirius" # for configuration
width = 2688
height = 1520
rotate180 = true
rotate90 = false
position = [0.0, 0.0, 0.15]
orientation_hpr = [0.0, -90.0, 0.0]

# The optical sensor size of the CAMERA, width and height in mm
# This should typically be in the same ratio as the resolution, above.
sensor_size_wh_mm = [4.76, 3.57]
focal_length_mm = 2.1
