ports = [
        # "/dev/serial/by-id/usb-CUAUV_Aurora_1_AUV1-6T17DG-if01-port0", #merge
        # "/dev/serial/by-id/usb-CUAUV_Aurora_2_AUV2-6ZMS9N-if00-port0", #sensor
        # "/dev/serial/by-id/usb-CUAUV_Aurora_2_AUV2-6ZMS9N-if01-port0", #actuators
        # "/dev/serial/by-id/usb-CUAUV_Aurora_2_AUV2-6ZMS9N-if02-port0", #PD
        # "/dev/serial/by-id/usb-CUAUV_Aurora_3_AUV3-7OAXTQ-if00-port0", #Transmit
        # "/dev/serial/by-id/usb-CUAUV_Aurora_4_AUV4-6O7D1T-if02-port0", #Thrust1
        # "/dev/serial/by-id/usb-CUAUV_Aurora_4_AUV4-6O7D1T-if01-port0" #THrust2
        "/dev/serial/by-id/usb-CUAUV_Kraken_3_AUV-KRAKEN3-if02-port0", # merge
        "/dev/serial/by-id/usb-CUAUV_Kraken_2_AUV-KRAKEN2-if02-port0", # PD
        "/dev/serial/by-id/usb-CUAUV_Kraken_4_AUV-KRAKEN4-if02-port0", # thruster 2
        "/dev/serial/by-id/usb-CUAUV_Kraken_1_AUV-KRAKEN1-if00-port0", # thruster 1
        "/dev/serial/by-id/usb-CUAUV_Kraken_4_AUV-KRAKEN4-if00-port0", # sensor
        "/dev/serial/by-id/usb-CUAUV_Kraken_2_AUV-KRAKEN2-if03-port0", # actuators
        "/dev/ttyUSB5" # transmit
]

