[devices.actuators.vars]
Motor1 = "actuator_desires.motor_pwm_1"
Motor1Current = "actuator_status.motor_current_1"
VccFuse = "actuator_status.vcc_fuse_blown"
HBFuse = "actuator_status.hb_fuse_blown"

Act0Trigger = "actuator_desires.trigger_00"
Act1Trigger = "actuator_desires.trigger_01"
Act2Trigger = "actuator_desires.trigger_02"
Act3Trigger = "actuator_desires.trigger_03"
Act4Trigger = "actuator_desires.trigger_04"
Act5Trigger = "actuator_desires.trigger_05"
Act6Trigger = "actuator_desires.trigger_06"
Act7Trigger = "actuator_desires.trigger_07"
Act8Trigger = "actuator_desires.trigger_08"
Act9Trigger = "actuator_desires.trigger_09"
Act10Trigger = "actuator_desires.trigger_10"
Act11Trigger = "actuator_desires.trigger_11"
Act12Trigger = "actuator_desires.trigger_12"
Act13Trigger = "actuator_desires.trigger_13"

G1DC = "actuator_status.g1dc"
G2DC = "actuator_status.g2dc"
G3DC = "actuator_status.g3dc"
G4DC = "actuator_status.g4dc"
