[devices.actuators.vars]
Act0On = "actuator_desires.act_0_on"
Act1On = "actuator_desires.act_1_on"
Act2On = "actuator_desires.act_2_on"
Act3On = "actuator_desires.act_3_on"
Act0PwmVal = "actuator_desires.act_0_pwm" 
Act1PwmVal = "actuator_desires.act_1_pwm"
Act2PwmVal = "actuator_desires.act_2_pwm"
Act3PwmVal = "actuator_desires.act_3_pwm"
RampPeriod = "actuator_desires.ramp_period"
RampInc = "actuator_desires.ramp_inc"
RampDec = "actuator_desires.ramp_dec"

Act0OnReadback = "actuator_status.act_0_on_readback"
Act1OnReadback = "actuator_status.act_1_on_readback"
Act2OnReadback = "actuator_status.act_2_on_readback"
Act3OnReadback = "actuator_status.act_3_on_readback"
Act0PwmReadback = "actuator_status.act_0_pwm_readback"
Act1PwmReadback = "actuator_status.act_1_pwm_readback"
Act2PwmReadback = "actuator_status.act_2_pwm_readback"
Act3PwmReadback = "actuator_status.act_3_pwm_readback"
RampPerReadback = "actuator_status.ramp_per_readback" 
RampIncReadback = "actuator_status.ramp_inc_readback"
RampDecReadback = "actuator_status.ramp_dec_readback"

VccFuse = "actuator_status.vcc_fuse"

