[devices.thrusters2.vars]
Thruster2PwmVal = "motor_desires.aft_port"
Thruster4PwmVal = "motor_desires.port"
Thruster5PwmVal = "motor_desires.aft_starboard"
Thruster6PwmVal = "motor_desires.sway_fore"

Thruster2PwmReadback = "ramp_status.aft_port_ramp"
Thruster4PwmReadback = "ramp_status.port_ramp"
Thruster5PwmReadback = "ramp_status.aft_starboard_ramp"
Thruster6PwmReadback = "ramp_status.sway_fore_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"
