[devices.thruster_board_2.vars]
Thruster5PwmVal = "motor_desires.port"
Thruster6PwmVal = "motor_desires.aft_port"
Thruster7PwmVal = "motor_desires.starboard"
Thruster8PwmVal = "motor_desires.sway_aft"

Thruster5PwmReadback = "ramp_status.port_ramp"
Thruster6PwmReadback = "ramp_status.aft_port_ramp"
Thruster7PwmReadback = "ramp_status.starboard_ramp"
Thruster8PwmReadback = "ramp_status.sway_aft_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"
