[devices.thruster_board_1.vars]
Thruster1PwmVal = "motor_desires.sway_fore"
Thruster2PwmVal = "motor_desires.sway_aft"
Thruster3PwmVal = "motor_desires.fore_starboard"
Thruster4PwmVal = "motor_desires.starboard"

Thruster1PwmReadBack = "ramp_status.sway_fore_ramp"
Thruster2PwmReadBack = "ramp_status.sway_aft_ramp"
Thruster3PwmReadBack = "ramp_status.fore_starboard_ramp"
Thruster4PwmReadBack = "ramp_status.starboard_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"
