[devices.thruster_board_2.vars]
Thruster5PwmVal = "motor_desires.fore_starboard"
Thruster6PwmVal = "motor_desires.sway_fore"
Thruster7PwmVal = "motor_desires.starboard"
Thruster8PwmVal = "motor_desires.sway_aft"

Thruster5PwmReadback = "ramp_status.fore_starboard_ramp"
Thruster6PwmReadback = "ramp_status.sway_fore_ramp"
Thruster7PwmReadback = "ramp_status.starboard_ramp"
Thruster8PwmReadback = "ramp_status.sway_aft_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"

