[devices.Sensor.vars]
DepthOffsetWriteVar = "depth.offset"
DepthReadVar = "depth.depth"
PressureReadVar = "pressure.hull"
TemperatureReadVar = "temperature.hull"

LightShowWriteVar = "leds.light_show"
# Green and blue are flipped
PortColorRedWriteVar = "leds.port_color_red"
PortColorGreenWriteVar = "leds.port_color_blue"
PortColorBlueWriteVar = "leds.port_color_green"
StarboardColorRedWriteVar = "leds.starboard_color_red"
StarboardColorGreenWriteVar = "leds.starboard_color_blue"
StarboardColorBlueWriteVar = "leds.starboard_color_green"
