includes = [
    "siriusPorts.toml",
    "polarisThruster1.toml",
    "polarisThruster2.toml",
    "powerDistribution.toml",
    "sensor.toml",
    "actuator.toml",
    "merge.toml",
    "led.toml",
    "transmit.toml",
    "bmbPodA.toml",
    "bmbPodB.toml"
]

