[devices.transmit.vars]
NewDataWriteVar = "transmit_settings.new_data_write"
WordWriteVar = "transmit_settings.word_write"
SymbolRateWriteVar = "transmit_settings.symbol_rate"
BandwidthWriteVar = "transmit_settings.bandwidth"
SymbolSizeWriteVar = "transmit_settings.symbol_size"
FreqWriteVar = "transmit_settings.freq"
AckReadVar = "transmit_settings.ack_read"
