[package]
name = "rust_conf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "1.0.147"
serde = "1.0.147"
toml="0.5.9"
nalgebra = "0.31.2"
