name: Black (python)

on:
  pull_request:
    branches: [ master ]

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          CHANGED_PY_FILES=$(git diff --diff-filter=d --name-only $(git merge-base HEAD origin/master) HEAD | grep .py)
          echo "CHANGED_PY_FILES=$CHANGED_PY_FILES" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install black and reorder-python-imports
        run: pip install black reorder-python-imports

      - name: Run Black on changed files
        if: env.CHANGED_PY_FILES != ''
        run: black --check reorder-python-imports $CHANGED_PY_FILES

