name: Python Style Check

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: "**/*.py"

      - name: Setup Python env
        uses: actions/setup-python@v3

      - name: Install black and ruff
        run: pip install black ruff

      - name: Black
        continue-on-error: true
        if: ${{ steps.changed-files.outputs.all_changed_files }} != ""
        run: |
          black --verbose ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Ruff
        if: ${{ steps.changed-files.outputs.all_changed_files }} != ""
        run: |
          ruff check ${{ steps.changed-files.outputs.all_changed_files }}

